const ProductNameList = [
  { id: "p11", name: "A", value: "49" },
  { id: "p12", name: "B", value: "99" },
  { id: "p13", name: "C", value: "149" },
  { id: "p14", name: "D", value: "49" },
  { id: "p15", name: "E", value: "99" },
  { id: "p16", name: "F", value: "149" },
  { id: "p17", name: "G", value: "49" },
  { id: "p18", name: "H", value: "99" },
  { id: "p19", name: "I", Ivalue: "149" },
  { id: "p20", name: "J", value: "49" },
  { id: "p21", name: "K", value: "99" },
  { id: "p22", name: "L", value: "149" },
  // { id: "p11", name: "M", value: "49" },
  // { id: "p15", name: "N", value: "99" },
  // { id: "p13", name: "O", value: "149" },
  // { id: "p11", name: "P", value: "49" },
  // { id: "p15", name: "Q", value: "99" },
  // { id: "p13", name: "R", Ivalue: "149" },
  // { id: "p11", name: "S", value: "49" },
  // { id: "p15", name: "T", value: "99" },
  // { id: "p13", name: "U", value: "149" },
  // { id: "p11", name: "V", value: "49" },
  // { id: "p15", name: "W", value: "99" },
  // { id: "p13", name: "X", value: "149" },
  // { id: "p15", name: "Y", value: "99" },
  // { id: "p13", name: "Z", value: "149" },
];

export default ProductNameList;
